# Generated by Django 4.2.26 on 2025-11-17 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_image_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Карточка', 'verbose_name_plural': 'Карточки'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterModelOptions(
            name='withdrawrequest',
            options={'verbose_name': 'Запрос на вывод', 'verbose_name_plural': 'Запросы на вывод'},
        ),
    ]
