# Generated by Django 4.2.26 on 2025-11-23 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0003_alter_card_options_alter_userprofile_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, verbose_name="Название группы"),
                ),
                (
                    "drop_chance",
                    models.FloatField(
                        default=0.0,
                        help_text="Шанс выпадения (0-1)",
                        verbose_name="Шанс выпадения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа карточек",
                "verbose_name_plural": "Группы карточек",
            },
        ),
        migrations.AddField(
            model_name="card",
            name="animation",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="cards/animations/",
                verbose_name="JSON-анимация появления",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="referral_code",
            field=models.CharField(
                default="", max_length=12, unique=True, verbose_name="Реферальный код"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals",
                to="cards.userprofile",
                verbose_name="Пригласивший пользователь",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="telegram_stars_balance",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Баланс звёзд в Telegram"
            ),
        ),
        migrations.CreateModel(
            name="CardTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Обычная"),
                            ("rare", "Редкая"),
                            ("epic", "Эпическая"),
                            ("legendary", "Легендарная"),
                        ],
                        default="common",
                        max_length=32,
                        verbose_name="Редкость",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="cards/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "animation",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="cards/animations/",
                        verbose_name="JSON-анимация появления",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="cards.cardgroup",
                        verbose_name="Группа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблон карточки",
                "verbose_name_plural": "Шаблоны карточек",
            },
        ),
        migrations.AddField(
            model_name="card",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instances",
                to="cards.cardtemplate",
                verbose_name="Шаблон карточки",
            ),
        ),
    ]
