# Generated by Django 4.2.26 on 2025-11-23 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cards", "0004_cardgroup_card_animation_userprofile_referral_code_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="Card", new_name="CollectionCard"),
        migrations.AlterModelOptions(
            name="collectioncard",
            options={"verbose_name": "Коллекция", "verbose_name_plural": "Коллекции"},
        ),
        migrations.AlterModelTable(
            name="collectioncard",
            table="collection",
        ),
        migrations.RemoveField(
            model_name="collectioncard",
            name="quantity",
        ),
        migrations.AlterField(
            model_name="collectioncard",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collection_cards",
                to="cards.cardtemplate",
                verbose_name="Шаблон карточки",
            ),
        ),
        migrations.AlterField(
            model_name="collectioncard",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectioncard",
            constraint=models.UniqueConstraint(
                fields=("user", "template"), name="unique_user_card_template"
            ),
        ),
    ]
