# Generated by Django 4.2.26 on 2025-12-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_cardsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectioncard',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
