# Generated by Django 4.2.26 on 2025-12-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_collectioncard_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsettings',
            name='referral_reward',
            field=models.PositiveIntegerField(default=0, verbose_name='Награда за привлечённого пользователя (звёзды)'),
        ),
    ]
