# Generated by Django 4.2.26 on 2025-12-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_cardsettings_referral_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardgroup',
            name='color',
            field=models.CharField(default='#000000', max_length=16, verbose_name='Цвет группы (hex)'),
        ),
        migrations.AddField(
            model_name='cardgroup',
            name='rating',
            field=models.FloatField(default=1.0, help_text='Рейтинг группы (0.5 - 10)', verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='cardgroup',
            name='row_reward',
            field=models.PositiveIntegerField(default=0, verbose_name='Награда за собранный ряд'),
        ),
    ]
